# AUTO-GENERATED by sync-config - edit .aetherstack/ instead

param(
    [switch]$Check
)

$ErrorActionPreference = "Stop"
$Root = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
Set-Location $Root

function Write-Utf8NoBom {
    param([string]$Path, [string]$Content)
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, $Content, $utf8)
}

function Read-Utf8 {
    param([string]$Path)
    return [System.IO.File]::ReadAllText($Path, [System.Text.UTF8Encoding]::new($false))
}

$Banner = @"
<!-- AUTO-GENERATED - DO NOT EDIT -->
<!-- Edit .aetherstack/ then run: make sync-config -->

"@

# --- .cursorrules ---
$core = Read-Utf8 (Join-Path $Root ".aetherstack\rules\core.md")
$cursorrules = @"
$Banner
# AetherStack - Cursor Rules

$core

## See also

- AGENTS.md
- .aetherstack/rules/
- .aetherstack/manifest.yaml
"@
Write-Utf8NoBom (Join-Path $Root ".cursorrules") $cursorrules

# --- .cursor/rules/*.mdc ---
$cursorRulesDir = Join-Path $Root ".cursor\rules"
New-Item -ItemType Directory -Force -Path $cursorRulesDir | Out-Null
Get-ChildItem (Join-Path $Root ".aetherstack\rules") -Filter "*.md" | ForEach-Object {
    $name = "aether-$($_.BaseName).mdc"
    $body = Read-Utf8 $_.FullName
    $mdc = @"
---
description: AetherStack $($_.BaseName) rules
alwaysApply: true
---

$body
"@
    Write-Utf8NoBom (Join-Path $cursorRulesDir $name) $mdc
}

# 复制 README 到根目录（UTF-8 字节复制，避免 PowerShell 编码问题）
$src = Join-Path $Root "docs\README.full.md"
$dst = Join-Path $Root "README.md"
if (Test-Path $src) {
    $bytes = [System.IO.File]::ReadAllBytes($src)
    [System.IO.File]::WriteAllBytes($dst, $bytes)
}

# --- CLAUDE.md (from template, UTF-8 byte copy) ---
$claudeTemplate = Join-Path $Root ".aetherstack\templates\CLAUDE.md"
if (Test-Path $claudeTemplate) {
    $bytes = [System.IO.File]::ReadAllBytes($claudeTemplate)
    [System.IO.File]::WriteAllBytes((Join-Path $Root "CLAUDE.md"), $bytes)
}

# --- .codex/config.toml ---
$codexDir = Join-Path $Root ".codex"
New-Item -ItemType Directory -Force -Path $codexDir | Out-Null
$rulesList = Get-ChildItem (Join-Path $Root ".aetherstack\rules") -Filter "*.md" | ForEach-Object {
    $rel = ".aetherstack/rules/$($_.Name)"
    "  `"$rel`""
}
$toml = @"
# AUTO-GENERATED - edit .aetherstack/ then make sync-config

[project]
name = "AetherStack"
root = "."

[instructions]
agents = "AGENTS.md"
rules = [
$(($rulesList) -join ",`n")
]

[context]
manifest = ".aetherstack/manifest.yaml"
"@
Write-Utf8NoBom (Join-Path $codexDir "config.toml") $toml

# --- .codex/AGENTS.md ---
$agentsContent = Read-Utf8 (Join-Path $Root "AGENTS.md")
Write-Utf8NoBom (Join-Path $codexDir "AGENTS.md") $agentsContent

# --- .claude/settings.json ---
$claudeDir = Join-Path $Root ".claude"
New-Item -ItemType Directory -Force -Path $claudeDir | Out-Null
$settings = @{
    additionalDirectories = @(
        (Join-Path $Root "harness"),
        (Join-Path $Root "aether-skills"),
        (Join-Path $Root ".aetherstack")
    )
} | ConvertTo-Json -Depth 5
Write-Utf8NoBom (Join-Path $claudeDir "settings.json") $settings

Write-Host "sync-config completed (UTF-8 no BOM)"
